#https://tower-dle.ole.redhat.com/#/jobs/playbook/4932
## Disk names can be found from OpenStack Images and soon DLE-WEB

hdb:
  image_name: rh415-9.2-x86_64-additional-20230915
  disk_size: 6
  device_type: cdrom
  ilt_image_override: "*${RHELVER}*-additional*.iso"
